### ISSUE TITLE
about flash operation questions

### ISSUE THREAD

**Issue by flamecyclone** [ClusterM/coolgirl-multirom-builder#2]
After reading your code about flash operation, there are a few things I don't understand.

sector_erase:
  jsr enable_flash_write
  jsr flash_set_superbank
  #lda #$F0
  sta $8000 ; $F0 -> $0000
  lda #$AA
  sta $8AAA ; $AA -> $0AAA
  lda #$55
  sta $8555 ; $55 -> $0555
  lda #$80
  sta $8AAA ; $80 -> $0AAA
  lda #$AA
  sta $8AAA ; $AA -> $0AAA
  lda #$55
  sta $8555 ; $55 -> $0555
  lda #$30
  sta $8000 ; $30 -> $0000
  jsr disable_flash_write
  lda #$FF
.wait:
  cmp $8000
  bne .wait
  cmp $8000
  bne .wait
  jsr banking_init
  rts

write_flash:
  jsr enable_flash_write
  jsr flash_set_superbank
  ldy #$00
  ldx #$20
.loop:
  lda #$F0
  sta $8000 ; $F0 -> $0000
  lda #$AA
  sta $8AAA ; $AA -> $0AAA
  lda #$55
  sta $8555 ; $55 -> $0555
  lda #$A0
  sta $8AAA ; $A0 -> $0AAA
  lda [COPY_SOURCE_ADDR], y
  sta [COPY_DEST_ADDR], y
.wait:
  cmp [COPY_DEST_ADDR], y
  bne .wait
  cmp [COPY_DEST_ADDR], y
  bne .wait
  iny
  bne .loop
  inc <COPY_SOURCE_ADDR+1
  inc <COPY_DEST_ADDR+1
  dex
  bne .loop
  jsr disable_flash_write
  jsr banking_init
  rts

I don't understand the following two things, so I ask you for help

1.The code in the sector_erase
  lda #$F0
  sta $8000 ; $F0 -> $0000
  lda #$AA
  sta $8AAA ; $AA -> $0AAA
  lda #$55
  sta $8555 ; $55 -> $0555
  lda #$80
  sta $8AAA ; $80 -> $0AAA
  lda #$AA
  sta $8AAA ; $AA -> $0AAA
  lda #$55
  sta $8555 ; $55 -> $0555
  lda #$30
  sta $8000 ; $30 -> $0000

2.The code in the write_flash
  lda #$F0
  sta $8000 ; $F0 -> $0000
  lda #$AA
  sta $8AAA ; $AA -> $0AAA
  lda #$55
  sta $8555 ; $55 -> $0555
  lda #$A0

**Comment by flamecyclone** [comment]
In addition, the scratch granularity of flash is 128KB, can't it be smaller, such as 8KB, 16KB
![image](https://github.com/ClusterM/coolgirl-multirom-builder/assets/70200943/6537e990-2de6-42d9-bc8b-0a181e4a99a8)

**Comment by ClusterM** [comment]
Hi. This flash memory has sectors of 128KB. It's impossible to erase a smaller region.
> I don't understand the following two things, so I ask you for help
1.The code in the sector_erase
lda #$F0
sta $8000 ; $F0 -> $0000
lda #$AA
sta $8AAA ; $AA -> $0AAA

It's commands to the flash memory chip. You can find all commands in the datasheet.

![image](https://github.com/ClusterM/coolgirl-multirom-builder/assets/4236181/590dd41c-b805-45dc-a997-72a063858280)

![image](https://github.com/ClusterM/coolgirl-multirom-builder/assets/4236181/74684c28-e57f-44bd-9864-e308fc7117b2)
