### ISSUE TITLE
Сломалась сборка make

### ISSUE THREAD

**Issue by JRBVZz** [ClusterM/coolgirl-multirom-builder#5]
Привет. С последним изменением стало невозможно собрать итоговые файлы. Помогает копирование папки tools из последнего релиза.

**Comment by ClusterM** [comment]
Привет. А какая ошибка-то? Какая платформа? Речь именно о последнем коммите?

**Comment by JRBVZz** [comment]
Да, нет папки tools со всеми программами для создания мультирома: nesasm, nestiler, coogirl-combiner.
